library(shinycustomloader)
library(tidyverse)
navbarPage(
  "G protein coupled receptor (GPCR) research hotness Trend (1946-2019)",
  tabPanel(
    "G protein coupled receptors research trend in GPCR filed",
    fluidPage(
      wellPanel(
        h4("What is this?"),
        p("GPCR is the largest protein family of drug targets. 
          This project analyzed 300k+ paper with 'G protein coupled receptor' 
          in abstracts as a domain specific literature input. Note: The results 
          are generated by machine learning, not verified by human. copyright@shirley, email:shunling.guo@gmail.com"),
        p("By selecting the receptor in tab, you may see the research 
        paper number of this receptor in GPCR specific domain normalized 
        to the total paper published in GPCR domain that year, i.e.
          research hotness index. You can also see top15 closest words with that receptor
          and its topic class with confidence score.")
      ),
      
      div(
        fluidRow(
          column(
            selectInput("selected_receptor",
              "Select a receptor",
              choices = NULL
            ),
            width = 3
          )
        ),
        style = "position:relative;z-index:10000;"
      )
    ),
    
    actionButton("update_chart",
      "See Insights",
      width = "100%"
    ),
    
    hr(),
    
    fluidRow(
      column(
        withLoader(plotOutput("Receptor_hotness"), loader = "dnaspin"),
        width = 9
      )
    ),
    
    fluidRow(
      column(
        withLoader(tableOutput("Top15"), loader = "dnaspin"),
        width = 3
      )
    ),
   
    fluidPage(
      wellPanel("For the receptors appeared in the same paper, a connection is established
        between them. The thickness of line represents connection strength, and the 
        size of the circle represents paper number regarding that recetpor in GPCR domain."),
      
      imageOutput("connectome")
    )
    
  ),
  collapsible = TRUE
)
